#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessPausedMenuSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_
