#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessCryptSceneInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_