#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessGraveyardSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_