#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessSettingsMenuSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_