#ifndef SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETESCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETESCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessLevelCompleteSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETESCENEINPUTEVENT_HPP__
