#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessRuinSceneLowerInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_