#ifndef SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessPausedMenuSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP__
