#ifndef SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessRuinSceneUpperInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP__
