#ifndef SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessGameoverSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP__
