#ifndef SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessRuinSceneLowerInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP__
