#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessRuinSceneUpperInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_