#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessPausedMenuSceneInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSPAUSEDMENUSCENEINPUTEVENT_HPP_
