#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessRuinSceneUpperInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENEUPPERINPUTEVENT_HPP_