#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessTitleSceneInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_