#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessShopSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP_