#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessGameoverSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSGAMEOVERSCENEINPUTEVENT_HPP_
