#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessCryptSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP_