#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessRuinSceneLowerInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSRUINSCENELOWERINPUTEVENT_HPP_