#ifndef SRC_SCENECONTROL_EVENTS_PROCESSSETTINGSMENUSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSSETTINGSMENUSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessSettingsMenuSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSSETTINGSMENUSCENEINPUTEVENT_HPP__
