#ifndef SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessGraveyardSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP__
