#ifndef SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessShopSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSSHOPSCENEINPUTEVENT_HPP__
