#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessLevelCompleteSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSLEVELCOMPLETEINPUTEVENT_HPP_