#ifndef SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessTitleSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP__
