#ifndef SRC_SCENECONTROL_EVENTS_PROCESSSACREDSPRINGSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSSACREDSPRINGSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessHealingSpringSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSSACREDSPRINGSCENEINPUTEVENT_HPP__
