#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_

namespace Game::Events
{

struct ProcessTitleSceneInputEvent
{
};

} // namespace Game::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSTITLESCENEINPUTEVENT_HPP_