#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessGraveyardSceneInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSGRAVEYARDSCENEINPUTEVENT_HPP_