#ifndef _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_
#define _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_

namespace ProceduralMaze::Events
{

struct ProcessSettingsMenuSceneInputEvent
{
};

} // namespace ProceduralMaze::Events

#endif // _SRC_SCENECONTROL_EVENTS_PROCESSSETTINGMENUSCENEINPUTEVENT_HPP_