#ifndef SRC_SCENECONTROL_EVENTS_PROCESSHOLYWELLSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSHOLYWELLSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessHolyWellSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSHOLYWELLSCENEINPUTEVENT_HPP__
