#ifndef SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP__
#define SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP__

namespace Game::Events
{

struct ProcessCryptSceneInputEvent
{
};

} // namespace Game::Events

#endif // SRC_SCENECONTROL_EVENTS_PROCESSCRYPTSCENEINPUTEVENT_HPP__
