#ifndef SRC_SPRITES_CIRCLESEGMENT_HPP__
#define SRC_SPRITES_CIRCLESEGMENT_HPP__

#include <vector>

namespace Game::Sprites
{

//! @brief A single angular arc segment of a circle, with its own visibility flag and a cached
//! vertex buffer regenerated only when the underlying geometry changes.
class CircleSegment
{
public:
  //! @brief Construct a new Circle Segment object
  //! @param start
  //! @param end
  //! @param vis
  CircleSegment( float start, float end, bool vis = true )
      : start_angle( start ),
        end_angle( end ),
        visible( vis )
  {
  }

  //! @brief Get the Bounds object
  //! @param center
  //! @param radius
  //! @param outline_thickness
  //! @return sf::FloatRect
  sf::FloatRect get_bounds( sf::Vector2f center, float radius, float outline_thickness ) const;

  //! @brief SFML draw function
  //! @param target
  //! @param states
  //! @param center
  //! @param radius
  //! @param outline_thickness
  //! @param color
  //! @param points_per_segment
  void draw( sf::RenderTarget &target, sf::RenderStates states, sf::Vector2f center, float radius, float outline_thickness, sf::Color color,
             int points_per_segment ) const;

  //! @brief Mark the cache as invalid to force segment vertices regen
  void invalidate_cache() const { vertices_dirty = true; }

  //! @brief Check if segment is visable
  //! @return true
  //! @return false
  bool is_visible() const { return visible; }

  //! @brief Get the segment Start Angle
  //! @return float
  float get_start_angle() const { return start_angle; }

  //! @brief Get the segment End Angle
  //! @return float
  float get_end_angle() const { return end_angle; }

private:
  //! @brief Angle, in radians, where this segment begins.
  float start_angle;
  //! @brief Angle, in radians, where this segment ends.
  float end_angle;
  //! @brief Whether this segment should be drawn.
  bool visible;

  //! @brief Vertex caching members
  //! @{
  //! @brief Cached vertex buffer generated by generate_vertices().
  mutable std::vector<sf::Vertex> cached_vertices;
  //! @brief True when cached_vertices no longer matches the current parameters and must be regenerated.
  mutable bool vertices_dirty = true;
  //! @brief Radius used to build the cached vertices.
  mutable float cached_radius = -1.0f;
  //! @brief Outline thickness used to build the cached vertices.
  mutable float cached_outline_thickness = -1.0f;
  //! @brief Center position used to build the cached vertices.
  mutable sf::Vector2f cached_position = { -1.0f, -1.0f };
  //! @brief Color used to build the cached vertices.
  mutable sf::Color cached_color = sf::Color::Transparent;
  //! @}

  //! @brief Regenerate cached_vertices for the current segment parameters.
  //! @param center Center of the circle this segment belongs to.
  //! @param radius Radius of the circle.
  //! @param outline_thickness Thickness of the outline geometry to generate.
  //! @param color Vertex color to apply.
  //! @param points_per_segment Number of points used to tessellate this segment.
  void generate_vertices( sf::Vector2f center, float radius, float outline_thickness, sf::Color color, int points_per_segment ) const;
};

} // namespace Game::Sprites

#endif // SRC_SPRITES_CIRCLESEGMENT_HPP__
