name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [debug, release, RelWithDebInfo, MinSizeRel]
      fail-fast: false
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: false
          load: true
          tags: local:latest
          
      - name: Run build with ${{ matrix.build_type }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/srv -w /srv local /srv/scripts/build.sh ${{ matrix.build_type }}