# action.yml
name: build
jobs:
  build:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    strategy:
      matrix:
        build_type: [debug, release, RelWithDebInfo, MinSizeRel]
    steps:
      - name: Build
        run: |
          chmod +x ${{ github.workspace }}/scripts/build.sh
          ${{ github.workspace }}/scripts/build.sh ${{ matrix.build_type }}

