# action.yml
name: build
runs:
  using: 'docker'
  image: 'Dockerfile'
jobs:
  build:
    strategy:
      matrix:
        build_type: [debug, release, RelWithDebInfo, MinSizeRel]
    steps:
      - name: Build
        run: |
          chmod +x ${{ github.workspace }}/scripts/build.sh
          ${{ github.workspace }}/scripts/build.sh ${{ matrix.build_type }}

